GoogleCloudPlatform/getting-started-dotnet

aspnet/2-structured-data/2-structured-data.csproj, aspnet/2-structured-data/packages.config
I don't understand why.  But this fixes nuget restore and build.
=> A couple package version changes fixes the build.

aspnet/2-structured-data/Models/Book.cs, aspnet/6-pubsub/lib/Models/Book.cs
Described here:
http://odetocode.com/blogs/scott/archive/2012/03/11/complete-guide-to-mass-assignment-in-asp-net-mvc.aspx
=> Use Bind attribute to defend against mass assignment attack.

buildAndRunTests.ps1
Fixes problem where buildAndRunTests.ps1 failed when run from the root directory.
=> Fix buildAndRunTests.ps1

aspnet/4-auth/App_Start/Startup.cs, aspnet/4-auth/Controllers/BooksController.cs, aspnet/4-auth/Controllers/SessionController.cs, aspnet/4-auth/Models/DatastoreBookStore.cs, aspnet/4-auth/Models/User.cs, aspnet/4-auth/Views/BookshelfWebViewPage.cs, aspnet/4-auth/Views/Shared/_Layout.cshtml, aspnet/4-auth/Views/Web.config
This includes documentation regions for the `4-auth` sample as well as some code changes to support documentation, eg. to add clarity
=> Authenticating with Google: code & doc region changes

buildAndRunTests.ps1
=> Order tests by name, so they run in order.

aspnet/2-structured-data/Models/DatastoreBookStore.cs, aspnet/3-binary-data/App_Start/UnityConfig.cs, aspnet/3-binary-data/Models/DatastoreBookStore.cs, aspnet/3-binary-data/Web.config, aspnet/5-pubsub/bookshelf/App_Start/UnityConfig.cs, aspnet/5-pubsub/bookshelf/Web.config, aspnet/5-pubsub/lib/Models/DatastoreBookStore.cs
The application name appears in the user agent string.  This will be a
useful metric for seeing how many people complete each step.
=> Set the ApplicationName to Bookshelf.Net-StepN.

BuildAndRunTests.ps1, BuildTools.psm1
So that we can test if the most recently released packages will break our
bookshelf.
=> Implement an -UpdatePackages flag.

aspnet/2-structured-data/App_Start/UnityConfig.cs, aspnet/3-binary-data/App_Start/UnityConfig.cs, aspnet/5-pubsub/lib/App_Start/UnityConfig.cs
I thought I had implemented this already.  But I guess I lost it in a branch that was abandoned.
=> Stop checking environment variables for app settings.

aspnet/5-pubsub/lib/Services/BookDetailLookup.cs, aspnet/5-pubsub/test/BookDetailLookupTest.cs, aspnet/6-auth/lib/Services/BookDetailLookup.cs, aspnet/6-auth/test/BookDetailLookupTest.cs
=> Update pubsub nomenclature.

aspnet/2-structured-data/2-structured-data.csproj, aspnet/2-structured-data/Web.config, aspnet/2-structured-data/packages.config, aspnet/3-binary-data/3-binary-data.csproj, aspnet/3-binary-data/Web.config, aspnet/3-binary-data/packages.config, aspnet/5-pubsub/bookshelf/Web.config, aspnet/5-pubsub/bookshelf/bookshelf.csproj, aspnet/5-pubsub/bookshelf/packages.config, aspnet/5-pubsub/lib/Services/BookDetailLookup.cs, aspnet/5-pubsub/lib/app.config, aspnet/5-pubsub/lib/lib.csproj, aspnet/5-pubsub/lib/packages.config, aspnet/5-pubsub/test/app.config, aspnet/5-pubsub/worker/Web.config, aspnet/6-auth/bookshelf/Web.config, aspnet/6-auth/bookshelf/bookshelf.csproj, aspnet/6-auth/bookshelf/packages.config, aspnet/6-auth/lib/Services/BookDetailLookup.cs, aspnet/6-auth/lib/app.config, aspnet/6-auth/lib/lib.csproj, aspnet/6-auth/lib/packages.config, aspnet/6-auth/test/app.config, aspnet/6-auth/worker/Web.config
Unfortunately, this doesn't fix the failing -with-latest-packages test.  I haven't found a way to fix that one yet.
=> Update some packages

BuildTools.psm1
=> Retry casperjs tests when they fail.

aspnet/5-pubsub/lib/Services/BookDetailLookup.cs, aspnet/6-auth/lib/Services/BookDetailLookup.cs
Handle non-null response with zero messages received.
=> Fix bug in pubsub acknowledge code.

.gitignore, .kokoro-windows/common.cfg, .kokoro-windows/trampoline.ps1, BuildTools.psm1, aspnet/1-hello-world/test.js, aspnet/2-structured-data/runTestsWithDatastore.ps1, aspnet/2-structured-data/runTestsWithSql.ps1, aspnet/2-structured-data/runTestsWithSqlServer.ps1, aspnet/2-structured-data/test.js, aspnet/3-binary-data/runTestsWithDatastore.ps1, aspnet/3-binary-data/runTestsWithSql.ps1, aspnet/3-binary-data/runTestsWithSqlServer.ps1, aspnet/3-binary-data/test.js, aspnet/5-pubsub/bookshelf/runTestsWithDatastore.ps1, aspnet/5-pubsub/bookshelf/runTestsWithSql.ps1, aspnet/5-pubsub/bookshelf/runTestsWithSqlServer.ps1, aspnet/5-pubsub/bookshelf/test.js, aspnet/5-pubsub/worker/runTestsWithDatastore.ps1, aspnet/5-pubsub/worker/runTestsWithSql.ps1, aspnet/5-pubsub/worker/runTestsWithSqlServer.ps1, aspnet/5-pubsub/worker/test.js, aspnet/6-auth/bookshelf/runTestsWithDatastore.ps1, aspnet/6-auth/bookshelf/runTestsWithSql.ps1, aspnet/6-auth/bookshelf/runTestsWithSqlServer.ps1, aspnet/6-auth/bookshelf/test.js, aspnet/6-auth/worker/runTestsWithDatastore.ps1, aspnet/6-auth/worker/runTestsWithSql.ps1, aspnet/6-auth/worker/runTestsWithSqlServer.ps1, aspnet/6-auth/worker/test.js
So we generate sponge_log.xmls and rendered test results in sponge
and test fusion.
=> Migrate casper tests to casper 1.1.

aspnet/5-pubsub/test/BookDetailLookupTest.cs
Same fix as https://github.com/GoogleCloudPlatform/getting-started-dotnet/pull/108
Change-Id: Ic5646b54896c36bac6333c839aac69136a0dfe54
=> Propagate test fix to same test in step 5.

aspnet/2-structured-data/packages.config, aspnet/3-binary-data/packages.config, aspnet/5-pubsub/bookshelf/packages.config, aspnet/6-auth/bookshelf/packages.config
Change-Id: I66332e476bfaedc26e7c9d2e5e945f3ab538d62f
=> Upgrade bootstrap lib to avoid known vulnerability.

Bookshelf/Bookshelf.csproj, Bookshelf/Dockerfile, Bookshelf/Enable-Apis.ps1, Bookshelf/Program.cs, Bookshelf/PublishTo-CloudRun.ps1, Bookshelf/Startup.cs
Required some scripts and some code changes.
=> Deploy bookshelf to Google CLoud Run.

.gitignore, HelloWorld/Dockerfile, HelloWorld/HelloWorld.csproj, HelloWorld/HelloWorld.sln, HelloWorld/Program.cs, HelloWorld/Properties/PublishProfiles/ComputeEngine.pubxml, HelloWorld/Properties/launchSettings.json, HelloWorld/PublishTo-CloudRun.ps1, HelloWorld/PublishTo-ComputeEngine.ps1, HelloWorld/Startup.cs, HelloWorld/appsettings.Development.json, HelloWorld/appsettings.json, HelloWorld/runTests.ps1, HelloWorld/test.js
Unlike earlier Compute Engine samples, this one is built on .NET core
instead of .NET framework.
=> A new Compute Engine HelloWorld sample.

Bookshelf/Models/FirestoreBookStore.cs, Bookshelf/Services/ImageUploader.cs
Change-Id: I82c8db648d3b120ab724009c7543276726e4ec84
=> Add some region tags.

BackgroundProcessing/TranslateUI/runTests.ps1, Bookshelf/Bookshelf.csproj, Bookshelf/Dockerfile, Bookshelf/Models/FirestoreBookStore.cs, Bookshelf/Program.cs, Bookshelf/Properties/launchSettings.json, Bookshelf/PublishTo-CloudRun.ps1, Bookshelf/Startup.cs, Bookshelf/Views/Books/Form.cshtml, Bookshelf/runTestsWithFirestore.ps1, Bookshelf/runTestsWithSqlInMemory.ps1, Bookshelf/test.js, BuildTools.psm1, HelloWorld/runTests.ps1, Sessions/runTests.ps1
Change-Id: I30742cd09d4ebe0cb930dfd8146314f26b87f53a
=> Downgrade bookshelf to dotnet 2.1

Sessions/Dockerfile, Sessions/PublishTo-CloudRun.ps1, Sessions/Sessions.csproj
from dotnet 2.2, because 2.1 is LTS.
Change-Id: I2ff687b0a5e5d7b0ae57d8ad580a3b8c144e5572
=> Downgrade sessions sample to dotnet 2.1

HelloWorld/PublishTo-ComputeEngine.ps1
Change-Id: I3e3353e7956ddff0168c087b934054f17b8c034d
=> Wrap dotnet publish command to 80 characters.

Sessions/Startup.cs
Change-Id: Ieb05b7ce7884b4b656117670bdd1efd24b30c16d
=> Add tag getting_started_sessions_configure_services

Sessions/appsettings.json
The docs and Set-Up.ps1 expect the key to be named masterkey.
=> Make Sessions/appsettings.json agree with docs.
